name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy EC2
      run: |
        echo "${{secrets.KEY_EC2}}" > private_key && chmod 400 private_key
        ssh -o StrictHostKeyChecking=no -i "private_key" ubuntu@ec2-100-29-88-215.compute-1.amazonaws.com "
          cd /var/www/html/ &&
          sudo git pull "
